const EmployeeActionTypes = {
  LOAD_REMAINING_HOURS_START: 'LOAD_REMAINING_HOURS_START',
  LOAD_REMAINING_HOURS_SUCCESS: 'LOAD_REMAINING_HOURS_SUCCESS',
  LOAD_REMAINING_HOURS_FAILURE: 'LOAD_REMAINING_HOURS_FAILURE'
};
export default EmployeeActionTypes;
