const EmployeeActionTypes = {
  LOAD_REMAINING_HOURS_START: 'LOAD_REMAINING_HOURS_START',
  LOAD_REMAINING_HOURS_SUCCESS: 'LOAD_REMAINING_HOURS_SUCCESS',
  LOAD_REMAINING_HOURS_FAILURE: 'LOAD_REMAINING_HOURS_FAILURE',
  LOAD_ASSIGNEE_START: 'LOAD_ASSIGNEE_START',
  LOAD_LOAD_ASSIGNEE_SUCCESS: 'LOAD_LOAD_ASSIGNEE_SUCCESS',
  LOAD_LOAD_ASSIGNEE_FAILURE: 'LOAD_LOAD_ASSIGNEE_FAILURE'
};
export default EmployeeActionTypes;
